### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by danielkucera** [LieBtrau/pulse-dtmf-converter#2]
Hello,
can you please provide pdf schematic, ideally into releases? 
I don't have altium and the web viewer refuses to show it (https://www.altium.com/viewer/)

Thank you.

**Comment by LieBtrau** [comment]
Hi Daniel,
The pcb-design is on [EasyEDA](https://easyeda.com/LieBtrau/New_Project-06f8d9abfb004e898edb54cca7790566).  You can immediately find the schematic and pcb-design there.  You could even start to change it if you want, no need to download any software.
The schematic on EasyEDA is R2, while the release on github is still R1.  I don't feel much for making a new github release, as there's no change in code on github and it has been some years now that I had a look at this project.
If you had clicked on the link in the readme of this github, you would also have found this (just like >3.5K people before you ;-) ).

**Comment by danielkucera** [comment]
Hello Christoph,
thanks for the response.
I've of course read the hackaday page, but imagine you are looking for schematics and you read this:
```
Firmware source code can be found on :  [GitHub](https://github.com/LieBtrau/pulse-dtmf-converter).  
Production data (hex-files, gerber files, schematics, ...) can be found on : [GitHub project's releases](https://github.com/LieBtrau/pulse-dtmf-converter/releases)
PCB design files are online on [EasyEda](https://easyeda.com/LieBtrau/New_Project-06f8d9abfb004e898edb54cca7790566).  The PCB design files have also been exported to Altium format and have been added to the repository on [GitHub](https://github.com/LieBtrau/pulse-dtmf-converter).  The contents of these Altium files has not been checked.
```
Where would you go looking for schematics?

**Comment by LieBtrau** [comment]
Well Daniel, you were right.  There were no schematics in there.
So, for your and everyone else's convenience, I've added a schematic in release R1.

**Comment by jhonniedj** [comment]
Is the project still on easyeda? or is it possible to create a BOM  and CPL to create the PCB from JLCPCB?

**Comment by LieBtrau** [comment]
Hi Jonathan,

The link to EasyEDA seems to be broken.  When I get back from holiday,
I'll look into to it and try to fix it.

Regards,

Christoph

**Comment by LieBtrau** [comment]
Hi Jonathan,
I fixed the broken link.  Apparently the link to EasyEDA only works when you're logged in.  Sorry for that.  

FYI : For my new projects, I switched to KiCad.  I own the files now and I'm no longer tied to a whimsical web service.

**Comment by jhonniedj** [comment]
> Hi Jonathan, I fixed the broken link. Apparently the link to EasyEDA only works when you're logged in. Sorry for that.
> 
> FYI : For my new projects, I switched to KiCad. I own the files now and I'm no longer tied to a whimsical web service.

Do you mean the EasyEDA link from your post on [Mar 15, 2022](https://github.com/LieBtrau/pulse-dtmf-converter/issues/2#issuecomment-1068307730), because when I open the URL after logging in to my account I get: 
```The project you are trying to access is either unpublished or does not exist.```
(screenshot below)


If it's not possible to make the project public on EasyEDA, is it possible to export a BOM and CPL file?

<img width="1045" height="891" alt="Image" src="https://github.com/user-attachments/assets/9bcc4560-ae12-4541-9dc7-079d31062773" />

**Comment by LieBtrau** [comment]
Hi Jonathan,
The process for making the project public was not complete yet.  I updated it and now it's in the "review phase".
Meanwhile I also added the BoM and P&P to the [R3 release data](https://github.com/LieBtrau/pulse-dtmf-converter/releases/tag/R3).  It should be possible to order it now on JLCPCB without too much hassle.  

For the orientation of the SOIC8 devices, you can check the assembly drawing.  There's no pin one marking in silk.

**Comment by jhonniedj** [comment]
> Hi Jonathan, The process for making the project public was not complete yet. I updated it and now it's in the "review phase". Meanwhile I also added the BoM and P&P to the [R3 release data](https://github.com/LieBtrau/pulse-dtmf-converter/releases/tag/R3). It should be possible to order it now on JLCPCB without too much hassle.
> 
> For the orientation of the SOIC8 devices, you can check the assembly drawing. There's no pin one marking in silk.

That is awesome! exactly what I needed! I think there are some components that can be basic vs advanced, I guess I can replace the 1206 to 0805 of 0603, and guess the attiny may be cheaper to buy and solder in the netherlands to cut cost (very dutch of me).
But... pushing gerber, BOM en CPL to JLCPCB look very promising! 🤩 

THANKS!

Although I may still wait to see the EasyEDA project when it reviewed.

**Comment by danielkucera** [comment]
Hi @jhonniedj ,

are you going to be making a batch of these?
I would be interested in buying a piece or two...

**Comment by LieBtrau** [comment]
> > Hi Jonathan, The process for making the project public was not complete yet. I updated it and now it's in the "review phase". Meanwhile I also added the BoM and P&P to the [R3 release data](https://github.com/LieBtrau/pulse-dtmf-converter/releases/tag/R3). It should be possible to order it now on JLCPCB without too much hassle.
> > For the orientation of the SOIC8 devices, you can check the assembly drawing. There's no pin one marking in silk.
> 
> That is awesome! exactly what I needed! I think there are some components that can be basic vs advanced, I guess I can replace the 1206 to 0805 of 0603, and guess the attiny may be cheaper to buy and solder in the netherlands to cut cost (very dutch of me). But... pushing gerber, BOM en CPL to JLCPCB look very promising! 🤩
> 
> THANKS!
> 
> Although I may still wait to see the EasyEDA project when it reviewed.

If I would do this project again, I would do things diffferently:
* use KiCad instead of EasyEDA
* provide a way to program the MCU on the PCB (e.g. provide test pads)
* The ATTiny85 is outdated in 2026, but I'm personally not willing to spend time porting it to a more recent MCU.
* Choose basic JLCPCB parts when possible (at least for the resistors and capacitors)
* The 1206-package was chosen for ease of hand soldering at the time, although today I'm generally using 0603 nowadays.  JLCPCB has a very limited offer on 1206 resistors in their "Basic Parts"-list, so 0603 would be a better choice.
